POST http://localhost:3333/events
Content-Type: application/json

{
    "title":"Essa porra não funciona",
    "details": "Um evento para quem é apaixondado por programação",
    "maximumAttendees": 100
}

### 

POST http://localhost:3333/events/9f917ae9-805e-4944-9406-a77cdf1b95c8/attendees
Content-Type: application/json

{
    "name" : "Renan Rapace",
    "email" : "renanrapace13@gmail.com" 
}

###

GET http://localhost:3333/events/9f917ae9-805e-4944-9406-a77cdf1b95c8

###

GET http://localhost:3333/attendees/10/badge

###

GET http://localhost:3333/attendees/10/check-in

###

GET http://localhost:3333/events/9f917ae9-805e-4944-9406-a77cdf1b95c8/attendees?query=Renan
