POST http://localhost:3333/events
Content-Type: application/json

{
    "title":"Essa porra não funciona",
    "details": "Um evento para quem é apaixondado por programação",
    "maximumAttendees": 100
}

### 

POST http://localhost:3333/events/9328582c-d1cd-415e-a379-e57082046115/attendees
Content-Type: application/json

{
    "name" : "Renan Rapace",
    "email" : "renanrapace13@gmail.com" 
}

###

GET http://localhost:3333/events/9328582c-d1cd-415e-a379-e57082046115

###

GET http://localhost:3333/attendees/10/badge

###

GET http://localhost:3333/attendees/10/check-in

###

GET http://localhost:3333/events/9328582c-d1cd-415e-a379-e57082046115/attendees?query=Renan
